# Name of the addon
name = "MySQL"

# Version of the addon
version = "1.1.0"
# Path to the main class of the addon
# Example: "com.example.exampleaddon.ExampleAddon"
#
# If this parameter is missing, your addon will not load
classPath = "de.erdbeerbaerlp.dcintegrationMySQL.MySQLAddon"

# Author of the Addon (optional)
author = "ErdbeerbaerLP"

# Description of the Addon (optional)
description = "Adds MySQL as a Database integration type"

APIVersion = 3